name: Get Unity License Activation File

on:
  workflow_dispatch:

jobs:
  request-alf:
    name: Request activation file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request manual activation file
        id: getAlf
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.3.2f1

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.3.2f1.alf
          path: ${{ steps.getAlf.outputs.filePath }}
